### PR TITLE
 Fixes #242. Directly return type string without further lookup

### LINKED ISSUE #242: type lookup in hint fails
Hi,

we're using the `codemirror-graphql` in the GraphQL Playground and experience problems, that the `type` property of a suggestion is undefined.
It happens in  this line of code:
https://github.com/graphql/codemirror-graphql/blob/master/src/hint.js#L66

The problem is, that `item.detail` can contain `!` in the case of a non-nullable type.
`item.detail` comes from here https://github.com/graphql/graphql-language-service/blob/master/packages/interface/src/getAutocompleteSuggestions.js#L97

`schema.getType()` however is just returning `getTypeMap()[name]` - as there is no type with the name `User!`, `undefined` is returned.
https://github.com/graphql/graphql-js/blob/master/src/type/schema.js#L182

Now is the question what the solution for this could be.
The quick-fix, that would work for us, is just not calling `.getType()` in `hint` anymore.
But I guess that the type lookup has been added for a reason.

@asiandrummer would be awesome to hear your take on that.

Thanks!

### PR DESCRIPTION
**Pull request by timsuchanek**

### CODE REVIEW

**Comment by yoshiakis** [comment]
This PR isn't still reviewed. Could anyone review it?

**Comment by acao** [comment]
Will look into this next week!

**Comment by yoshiakis** [comment]
@acao Thanks so much! :)

**Comment by benjie** [comment]
@yoshiakis Could you re-open this PR against https://github.com/graphql/graphiql/tree/master/packages/codemirror-graphql please? Assuming it gets merged, we'd like you to get credit. (This repository is being archived.)

**Comment by yoshiakis** [comment]
@benjie I open PR at graphql/graphiql#902!

**Comment by benjie** [comment]
Thanks!

**Pull request closed without merging**
