### PR TITLE
Allow GraphQL 0.12 as peer dependency

### PR DESCRIPTION
**Pull request by danez**
//cc @asiandrummer

### CODE REVIEW

**Comment by jamiehill** [comment]
Hi any progress on this PR?

**Comment by jamiehill** [comment]
That's fantastic news, thanks!

**Comment by benjie** [comment]
Hello, any idea when this release will be pushed out to npm?

**Comment by jamiehill** [comment]
Hi guys, any news on this?  Sorry to push, but blocked without this release, using the latest `graphiql`

**Pull request merged**
