### PR TITLE
Allow graphql 0.13 as peer dep

### PR DESCRIPTION
**Pull request by danez**
Also updates graphql + codemirror for the tests.

### CODE REVIEW

**Comment by moimael** [comment]
LGTM ?

**Comment by Yogu** [comment]
Especially since the last version bump to 0.12 has not yet been published to npm, it would be really great if this could be merged *and published* anytime soon.

This not only causes warnings but makes it really hard (or impossible) to find a supported graphql version in a simplified NPM environment like StackBlitz where peer dependencies are automatically resolved.

**Comment by danez** [comment]
@asiandrummer 🏓 🙂

**Comment by wmertens** [comment]
Had to remove graphiql from my build because of this not being merged yet :(

**Comment by keenubee** [comment]
Can we have it merged please?

**Comment by AGS-** [comment]
Hey everyone, sorry for the delay with this. @danez thanks for taking the time to do this.

**Pull request merged**
