### PR TITLE
Support directives hints for schema definitions

### PR DESCRIPTION
**Pull request by RomanGotsiy**
Add support for directives hints for schema definitions (schema shorthand notation)

image

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Just noticed this: https://github.com/graphql/graphql-language-service/blob/master/packages/graphql-language-service-interface/src/getAutocompleteSuggestions.js.

Should I transfer my changes there as well?

**Comment by RomanGotsiy** [comment]
@asiandrummer, I know you're working on `graphql-language-service`. Maybe you could comment

**Comment by asiandrummer** [comment]
@RomanGotsiy thanks for the contribution - your changes look awesome!
You're correct that this change should be mirrored to `graphql-language-service` as one of the packages in that repo (`graphql-language-service-interface` to be exact) should serve as the source of truth, but we haven't done that migration yet. I can take care of this when we get the migration happening ;)

I'm going to merge this - again thanks for the contribution!

**Comment by RomanGotsiy** [comment]
@asiandrummer awesome!

Btw wanted to ask about `graphql-language-service`. I need in IDL-editing functionality which is not working at the moment with `codemirror-graphql`:
- incomplete autosuggestion/linting for IDL
- you should pass it prebuilt schema which is not the case as the schema itself should be created/edited

Right now I have added a few hacks to make it work somehow in my project but I'm really interested to have it natively in language services. Is it in the scope? Can I help with this?

**Comment by asiandrummer** [comment]
@RomanGotsiy I'd greatly appreciate the help! I think `graphql-language-service` would be a perfect place to support those features. May I ask what your project does/is?

Within a couple days I should be able to: 1) merge your changes to `graphql-language-service`, and 2) use a shared library to achieve language service features in this repo. Feel free to PR to `graphql-language-service` repo with said features as you like, and I'll be sure to attend to them!

**Comment by RomanGotsiy** [comment]
I am working on a mock-server tool together with my college @IvanGoncharov. We leverage directives in IDL for configuring. For users to work easier with our tool we've set up a simple IDL editor. This PR adds support for autocompletion for directives which was the must for us.

image

But types autocompletion does not work + for example non-existing types are not linted, etc.
Moreover it doesn't pick up the changes from the edited IDL. So to have this working I am running `buildSchema` with each keystroke and if it doesn't fail I apply resulting schema to the editor :)

These problems are not limited to our tool. I believe this is a very common issue and I would love to help with this.

Let me know when you are ready with merging/refactoring this repo. Maybe we could chat then to discuss those features and ways to implement them.

**Comment by asiandrummer** [comment]
@RomanGotsiy definitely! Language service features for schema IDL is very interesting and would be of a high value if we can have it.

Just an intermediate idea - one way to achieve updating schema on the fly with added schema IDL is to pass the edited content for `onEdit` event from codemirror (any IDEs really), parse the query passed in, and extend the cached schema (in-memory) with found IDL nodes. In `GraphiQL`'s point of view, this could happen when the component mounts for the first time as well.

Let me open an issue and include you when I get the migration done ;)

**Comment by RomanGotsiy** [comment]
> parse the query passed in, and extend the cached schema (in-memory) with found IDL nodes. In GraphiQL's point of view, this could happen when the component mounts for the first time as well.

that't very similar to what I do :)

> Let me open an issue and include you when I get the migration done ;)
awesome! thank you!

**Pull request merged**
