### PR TITLE
This project is now part of the GraphQL IDE monorepo

### PR DESCRIPTION
**Pull request by benjie**
Lets start redirecting people to the new repo.

### CODE REVIEW

**Comment by benjie** [comment]
Hehe; I think we can ignore CI ;)

**Comment by acao** [comment]
@benjie i think the reason this is failing is because the dotfiles are still there, thus .travis.yml, etc

**Review by acao — CHANGES_REQUESTED** [review]
dotfiles too!

**Comment by benjie** [comment]
Whoops, yes!

**Review by acao — APPROVED** [review]

**Pull request merged**
