### PR TITLE
add deprecation info to hint list

### PR DESCRIPTION
**Pull request by 1aurabrown**
I would like to expose these values so that the graphql IDE can use them to let you know if an ENUM value is deprecated as you type, in the suggestions list. I will submit a PR to graphiql for that as well.

### CODE REVIEW

**Comment by asiandrummer** [comment]
Thanks @1aurabrown! GraphQL fields can be deprecated as well - could we include it in this PR or was there a reason why you didn't include it?

**Comment by leebyron** [comment]
Nice

**Comment by 1aurabrown** [comment]
hey @asiandrummer, i didn't see your message til now. i could do that some other time, this one just happened to be bugging me!

**Comment by 1aurabrown** [comment]
@leebyron @asiandrummer I see it's already been done. I was hoping to make a change to graphiql to show some visual indicator of the fact that a field or Enum is deprecated. How soon do you think you'll be making a release? I can update graphiql preemptively and assume that its dependencies will get updated the release with this change making the data available takes effect.

**Pull request merged**
